apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/chen-yu342/argocd-kafka-demo.git
    targetRevision: main
    path: kafka-clusters/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
