# Default values for kafka-ui
namespace: kafka-dev
replicaCount: 1
containerPort: 8080

image:
  repository: ghcr.io/kafbat/kafka-ui
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  nodePort: 30080

kafka:
  clusterName: "local-kraft"
  bootstrapServers: "my-kafka-kafka-bootstrap.kafka-dev.svc.cluster.local:9092"
  readonly: "false"

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"
